### ISSUE TITLE
Weird Unicode Error

### ISSUE THREAD

**Issue by KatoToyoki** [NOOBDY/GetQuestions#13]
running `./submit.exe` on Windows 10 shows this error
```
Traceback (most recent call last):
  File "submit.py", line 51, in <module>
  File "submit.py", line 35, in submit
  File "requests\sessions.py", line 590, in post
  File "requests\sessions.py", line 528, in request
  File "requests\sessions.py", line 456, in prepare_request
  File "requests\models.py", line 319, in prepare
  File "requests\models.py", line 512, in prepare_body
  File "requests\models.py", line 159, in _encode_files
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe5 in position 1184: illegal multibyte sequence
[6892] Failed to execute script 'submit' due to unhandled exception!
```

**Comment by kryr34** [comment]
can you provide submited file?
